apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.3.2
        env:
        - name: CLUSTER_NAME
          value: search
        resources:
          limits:
            cpu: 2000m
          requests:
            cpu: 200m
        ports:
        - containerPort: 5601
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 5601
            path: /api/status
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
          - name: config
            mountPath: /usr/share/kibana/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: kibana-config
